name: Rebuild Algolia Index
on: [page_build, workflow_dispatch]
jobs:
    refresh-index:
        name: Refresh Algolia Index
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout Sources
              uses: actions/checkout@v3
            - name: Setup Ruby
              uses: ruby/setup-ruby@v1
              with:
                ruby-version: '2.6' # Version range or exact version of a Ruby version to use, using semvers version range syntax.
            - name: Run Jekyll
              env: 
                ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
              run: |
                gem install bundler
                bundle install
                bundle exec jekyll algolia
  
