const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={articles:[]};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const href=a=>a?.url||'#';
function card(a){return `<article class="story">${a.image?`<a href="${esc(href(a))}"><img loading="lazy" src="${esc(a.image)}" alt="${esc(a.image_alt||'')}"></a>`:''}<div class="eyebrow">${esc(a.category||'News')}</div><h3><a href="${esc(href(a))}">${esc(a.title)}</a></h3><p>${esc(a.excerpt||'')}</p><div class="meta">${esc(a.source||'Evoford Journal')} · ${esc(a.date||'')}</div></article>`}
function render(list){state.articles=list||[];const [lead,...rest]=state.articles; if(lead){$('#hero').innerHTML=`<article class="heroLead"><a href="${esc(href(lead))}">${lead.image?`<img class="heroImage" src="${esc(lead.image)}" alt="${esc(lead.image_alt||'')}">`:''}<div class="eyebrow">${esc(lead.category||'News')}</div><h1>${esc(lead.title)}</h1><div class="deck">${esc(lead.excerpt||'')}</div><div class="meta">${esc(lead.source||'Evoford Journal')} · ${esc(lead.date||'')}</div></a></article>`} $('#rail').innerHTML=rest.slice(0,3).map(a=>`<article class="railStory"><div class="eyebrow">${esc(a.category||'News')}</div><h3><a href="${esc(href(a))}">${esc(a.title)}</a></h3><p>${esc(a.excerpt||'')}</p><div class="meta">${esc(a.date||'')}</div></article>`).join(''); $('#frontBottom').innerHTML=rest.slice(3,6).map(a=>`<article class="frontMini"><div class="eyebrow">${esc(a.category||'News')}</div><h3><a href="${esc(href(a))}">${esc(a.title)}</a></h3><div class="meta">${esc(a.date||'')}</div></article>`).join(''); $('#latestGrid').innerHTML=rest.slice(6,12).map(card).join('')||'<p class="meta">No stories yet.</p>'; ['Sustainability','Technology','Smart Cities','Waste & Operations','Perspective'].forEach(cat=>{const el=document.querySelector(`[data-category="${cat}"]`);if(el)el.innerHTML=state.articles.filter(a=>a.category===cat).slice(0,3).map(card).join('')||'<p class="meta">No stories yet.</p>'})}
async function load(){try{const r=await fetch('data/articles.json',{cache:'no-store'});if(!r.ok)throw Error(r.status);render(await r.json())}catch(e){console.error(e);$('#latestGrid').innerHTML='<p class="meta">Content is temporarily unavailable.</p>'}}
function setup(){const menu=$('#menuBtn'),mobile=$('#mobileMenu'),close=$('#menuClose');menu?.addEventListener('click',()=>mobile.classList.add('open'));close?.addEventListener('click',()=>mobile.classList.remove('open'));$$('.mobileMenu a').forEach(a=>a.addEventListener('click',()=>mobile.classList.remove('open')));const panel=$('#searchPanel'),open=$('#searchOpen'),x=$('#searchClose'),input=$('#searchInput'),results=$('#searchResults');open?.addEventListener('click',()=>{panel.classList.add('open');setTimeout(()=>input.focus(),50)});x?.addEventListener('click',()=>panel.classList.remove('open'));input?.addEventListener('input',()=>{const q=input.value.toLowerCase().trim();results.innerHTML=!q?'':state.articles.filter(a=>(a.title+' '+a.excerpt+' '+a.category).toLowerCase().includes(q)).slice(0,12).map(a=>`<a href="${esc(href(a))}">${esc(a.title)}<small class="meta">${esc(a.category||'News')} · ${esc(a.date||'')}</small></a>`).join('')})}
setup();load();
